name: B&D w/o Version
on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # Runs a single command using the runners shell
      - name: Build npm project and docs
        run: | 
          npm install
          npm run build
          npm run doc
      
      - name: Deploy Version
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: latest
      
      - name: Deploy redirect
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./redirect
          keep_files: true
